### ISSUE TITLE
Doesn't work with Antagonist shield

### ISSUE THREAD

**Issue by permagreen-zz** [LaryIsland/bl-sdk-mods#1]
When I try to combine Antagonist parts nothing happens and the console prints: 

`AttributeError: 'NoneType' object has no attribute 'WeightedParts'` 

So far this is the only item I've found with this error.

**Comment by LaryIsland** [comment]
Thanks for the report, should be fixed in bdd51f1 which will be part of v1.3

Gearbox decided the antagonist should use a different parts system than seemingly every other shield, which is why the bug affected just this one shield.
