### ISSUE TITLE
TPS issue

### ISSUE THREAD

**Issue by Zephyr-Shade** [LaryIsland/bl-sdk-mods#2]
Unlike in the BL2 version, it doesn't seem to work in the pre sequel on multiplayer. It just deletes the weapon for anyone who isn't the host.

**Comment by LaryIsland** [comment]
The multiplayer compatibility for BL2 happened mostly on accident.
If anyone is interested in fixing the multiplayer for TPS I'll gladly accept a pull request, otherwise I'll be leaving it as is.
