### ISSUE TITLE
Issue with Melee Enhancement Mod

### ISSUE THREAD

**Issue by mrmeeseeks1991** [LaryIsland/bl-sdk-mods#3]
I was really hyped for this mod, started a new Zero but whenever I enable this mod my game freezes after a couple melee attempts (Otherwise this doesnt occur). I can run around but the world itself freezes and my HUD is gone, cant shoot or melee afterwards.

**Comment by LaryIsland** [comment]
Very odd bug, do you have the krieg DLC installed?
Also would you be able to attach a screenshot of the issue?
